### ISSUE TITLE
Errors building and running on Ubuntu Linux 18.04

### ISSUE THREAD

**Issue by juozaspo** [minetest-tools/mtmapprune#1]
Trying to build on Ubuntu Linux 18.04 LTS (codename `bionic`) produces an error while running `make`, when `golang-go`, it's dependencies and `golang-github-mattn-go-sqlite3-dev` packages are already installed.
```
go build -ldflags "-X main.Version=3 -X main.Build=`git describe --tags --always`" -o mtmapprune
main.go:27:2: cannot find package "github.com/mattn/go-sqlite3" in any of:
	/usr/lib/go-1.10/src/github.com/mattn/go-sqlite3 (from $GOROOT)
	/home/juozas/go/src/github.com/mattn/go-sqlite3 (from $GOPATH)
Makefile:11: recipe for target 'mtmapprune' failed
make: *** [mtmapprune] Error 1
```
`golang-github-mattn-go-sqlite3-dev` package stores source files in subdirectory of `/usr/share/gocode/src/` and it appears go doesn't use this directory when it should (?), it uses `/usr/lib/go-1.10/src/` or `$HOME/go/src/` and can't find required files stored in other directories. Also there's no `github.com` directory in `/usr/lib/go-1.10/src/` and no symlinks linking to correct folder too.

**Edit:** Workaround: use `GOPATH=/usr/share/gocode make` command to build. Program then builds ok ~but isn't working properly:~ 
```
juozas@xubuntu:~/mtmapprune$ cp ~/minetest/worlds/world/map.sqlite .
juozas@xubuntu:~/mtmapprune$ ./mtmapprune map.sqlite 1000
panic: runtime error: index out of range

goroutine 1 [running]:
main.parse_arg(0x3, 0x3e8)
	/home/juozas/mtmapprune/main.go:42 +0x18c
main.main()
	/home/juozas/mtmapprune/main.go:72 +0xd4f

```
~**Edit2:** made a test build using debian with go 1.7.4, still fails:~
```
(debian)juozas@xubuntu:~/mtmapprune$ ./mtmapprune map.sqlite 1000
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x55f2fd03af80, 0xc420014150)
	/usr/lib/go-1.7/src/runtime/panic.go:500 +0x1a1
main.parse_arg(0x3, 0x3e8)
	/home/juozas/mtmapprune/main.go:42 +0x220
main.main()
	/home/juozas/mtmapprune/main.go:72 +0x10e4
```
**Edit3:** Above runtime issue is fixed in #2, now merged into master.

**Comment by sofar** [comment]
One day I'll have the time to make the Makefile smarter. Until then, you have to set GOPATH, that's just how `golang` works. You can also `go get ....` the dependencies and `go build` in the dependencies one by one. The Makefile just isn't really meant to be too smart, it's just meant to get my builds easily repeatable because I forget most of the trivial details when I cut a release, which isn't very often anyway....
