### ISSUE TITLE
Error: index out of range

### ISSUE THREAD

**Issue by sbrl** [minetest-tools/mtmapprune#3]
I'd love to use this tool, but it keep getting this error when using the latest release:

```
panic: runtime error: index out of range

goroutine 1 [running]:
main.parse_arg(0x4, 0x7d0)
	/home/sofar/git/mtmapprune/main.go:42 +0x1ef
main.main()
	/home/sofar/git/mtmapprune/main.go:74 +0xe5b
```

I see that a recent commit fixes the issue, but I don't think that made it into the latest release. As I don't have the go toolchain installed or know anything about compiling go programs, I can't, unfortunately, verify that the commit fixes the issue.

**Comment by sofar** [comment]
Try the v4 I just uploaded.

**Comment by sbrl** [comment]
No dice :-(

```
$ /tmp/mtmapprune-v4/mtmapprune worlds/WorldEdit-Test/map.sqlite 2500 2500
panic: runtime error: index out of range

goroutine 1 [running]:
main.parse_arg(0x4, 0x9c4)
	/home/sofar/git/mtmapprune/main.go:42 +0x18c
main.main()
	/home/sofar/git/mtmapprune/main.go:74 +0xd8b
```

**Comment by sofar** [comment]
Looks like I made a wrong build for the release. Try re-downloading the zip file again. I just published new zip files that should be OK.

**Comment by sbrl** [comment]
Yep, that works. thanks, @sofar :smiley_cat:
